#
# Copyright 2020 The TensorFlow Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

find_package(tfl-XNNPACK${LIBRARY_POSTFIX} QUIET CONFIG)
if(tfl-XNNPACK${LIBRARY_POSTFIX}_FOUND)
    report_found(tfl_XNNPACK "${tfl-XNNPACK${LIBRARY_POSTFIX}_VERSION}")
else()
    include(cmake/fp16_headers.cmake)

    fetch_git(NAME tfl-XNNPACK${LIBRARY_POSTFIX}
              REPO https://github.com/ILLIXR/XNNPACK.git
              TAG f8918b650876748517c7a5dd9b07b7f87bfe7d15
              NO_OVERRIDE
    )

    set(XNNPACK_BUILD_LIBRARY ON CACHE BOOL "" FORCE)
    set(XNNPACK_BUILD_TESTS OFF CACHE BOOL "" FORCE)
    set(XNNPACK_BUILD_BENCHMARKS OFF CACHE BOOL "" FORCE)
    set(XNNPACK_LIBRARY_TYPE static CACHE STRING "" FORCE)
    set(XNNPACK_USE_SYSTEM_LIBS ON CACHE BOOL "" FORCE)
    set(XNNPACK_ENABLE_AVXVNNI OFF CACHE BOOL "" FORCE)
    set(XNNPACK_ENABLE_ARM_FP16_SCALAR OFF CACHE BOOL "" FORCE)
    set(XNNPACK_ENABLE_ARM_FP16_VECTOR OFF CACHE BOOL "" FORCE)
    set(XNNPACK_ENABLE_JIT OFF CACHE BOOL "" FORCE)
    set(XNNPACK_ENABLE_SPARSE ON CACHE BOOL "" FORCE)
    set(XNNPACK_ENABLE_GEMM_M_SPECIALIZATION ON CACHE BOOL "" FORCE)
    set(XNNPACK_ENABLE_ASSEMBLY ON CACHE BOOL "" FORCE)
    set(XNNPACK_ENABLE_DWCONV_MULTIPASS ON CACHE BOOL "" FORCE)
    set(XNNPACK_ENABLE_MEMOPT ON CACHE BOOL "" FORCE)
    set(XNNPACK_ENABLE_AVX512AMX ON CACHE BOOL "" FORCE)
    set(XNNPACK_ENABLE_ARM_BF16 OFF CACHE BOOL "" FORCE)
    set(XNNPACK_ENABLE_ARM_DOTPROD OFF CACHE BOOL "" FORCE)
    set(XNNPACK_ENABLE_ARM_I8MM OFF CACHE BOOL "" FORCE)

    configure_target(NAME tfl-XNNPACK${LIBRARY_POSTFIX}
                     NO_FIND
    )
    set(tfl-XNNPACK${LIBRARY_POSTFIX}_DIR "${CMAKE_BINARY_DIR}" CACHE PATH "" FORCE)
    set(tfl-XNNPACK${LIBRARY_POSTFIX}_SOURCE_DIR "${tfl-XNNPACK_SOURCE_DIR}" CACHE PATH "" FORCE)
    unset(XNNPACK_BUILD_LIBRARY CACHE)
    unset(XNNPACK_BUILD_TESTS CACHE)
    unset(XNNPACK_BUILD_BENCHMARKS CACHE)
    unset(XNNPACK_LIBRARY_TYPE CACHE)
    unset(XNNPACK_USE_SYSTEM_LIBS CACHE)
    unset(XNNPACK_ENABLE_AVXVNNI CACHE)
    unset(XNNPACK_ENABLE_ARM_FP16_SCALAR CACHE)
    unset(XNNPACK_ENABLE_ARM_FP16_VECTOR CACHE)
    unset(XNNPACK_ENABLE_JIT CACHE)
    unset(XNNPACK_ENABLE_SPARSE CACHE)
    unset(XNNPACK_ENABLE_GEMM_M_SPECIALIZATION CACHE)
    unset(XNNPACK_ENABLE_ASSEMBLY CACHE)
    unset(XNNPACK_ENABLE_DWCONV_MULTIPASS CACHE)
    unset(XNNPACK_ENABLE_MEMOPT CACHE)
    unset(XNNPACK_ENABLE_AVX512AMX CACHE)
    unset(XNNPACK_ENABLE_ARM_BF16 CACHE)
    unset(XNNPACK_ENABLE_ARM_DOTPROD CACHE)
    unset(XNNPACK_ENABLE_ARM_I8MM CACHE)
    unset(tfl-XNNPACK_SOURCE_DIR CACHE)
    unset(tfl-XNNPACK_DIR CACHE)
endif()
